#!/bin/bash
# Usage: run_dis_hepmc <proc>
set -o errexit

# Input simulation parameters
eB=(5  5   10  10  18)
eA=(41 100 100 275 275)
j=$(( $1 % 100 ))
k=$(( $1 / 100 ))
eElectron=${eB[$k]}
eProton=${eA[$k]}
Q2min=1
min_e=$(echo "$eElectron * 0.02" | bc)
num_events=1000
physics_list="FTFP_BERT_HP"

OUTDIR=$SPIN/data/eic/endcap
WRKDIR=${OUTDIR}
#WRKDIR=${_CONDOR_SCRATCH_DIR}
mkdir -p ${OUTDIR} ${WRKDIR}

# Output file names
compact_file=../epic/epic_full.xml
info_string="pythia8NCDIS_${eElectron}x${eProton}_minQ2_${Q2min}-$j"
hepmc_file="${WRKDIR}/gen_${info_string}.hepmc"
abconv_file="${WRKDIR}/abc_${info_string}.hepmc"
abhist_file="${WRKDIR}/abc_${info_string}.hist.root"
sim_file="${WRKDIR}/sim_${info_string}.edm4hep.root"
rec_file_no_ext="${OUTDIR}/rec_${info_string}"

export DETECTOR_PATH=$EIC_SHELL_PREFIX/../epic
export BEAMLINE_PATH=$EIC_SHELL_PREFIX/../ip6
#export JANA_PLUGIN_PATH=$EIC_SHELL_PREFIX/lib/EICrecon/plugins

# Generating hepmc file
./pythia8/myepic-eq2 ${hepmc_file} ${eProton} ${eElectron} ${Q2min} ${num_events}
abconv ${hepmc_file} -o ${abconv_file%.hepmc} --plot-off
rm -f ${hepmc_file} ${abhist_file}

# Running simulation
cd ../epic
npsim --runType batch \
      -v WARNING \
      --part.minimalKineticEnergy "${min_e}*GeV" \
      --physics.list "FTFP_BERT_HP" \
      --physics.rangecut "None" \
      --numberOfEvents ${num_events} \
      --compactFile ${compact_file} \
      --inputFiles ${abconv_file} \
      --outputFile ${sim_file}

# Running JANA
cd ../EICrecon
eicrecon -Pjana:debug_plugin_loading=1 \
         -Pjana:nevents=${num_events} \
         -Pacts:MaterialMap=calibrations/materials-map.cbor \
         -Pdd4hep:xml_files=${compact_file} \
         -PBEMC:EcalBarrelScFiRawHits:signalSumFields="" \
         -Ppodio:output_file=${rec_file_no_ext}.tree.edm4eic.root \
         -Phistsfile=${rec_file_no_ext}.ana.root \
         ${sim_file}

#python3 ../analysis/attic/reco_flags.py \
#        --nevents ${num_events} \
#        --xml_files ${compact_file} \
#        ${sim_file} \
#        ${rec_file_no_ext}

# Deleting hepmc_file
rm -f ${abconv_file}
