#!/bin/bash
# Usage: run_sim_hepmc <proc> <particle>
set -o errexit

# Input simulation parameters
particle="$2"
energies=(65 70 80 90 100)
j=$(( $1 % 100 ))
k=$(( $1 / 100 ))
beam_energy=${energies[$k]}
min_e=$(echo "$beam_energy * 0.02" | bc)
num_events=1000
theta_min=4 # in degrees
theta_max=15 # in degrees
phi_min=0 # in degrees
phi_max=360 # in degrees 
physics_list="FTFP_BERT_HP"

WRKDIR=${_CONDOR_SCRATCH_DIR}
OUTDIR=$SPIN/data/eic/endcap
mkdir -p ${WRKDIR} ${OUTDIR}

# Output file names
compact_file=${DETECTOR_PATH}/epic.xml
info_string="${particle}_${beam_energy}GeV_theta_${theta_min}_${theta_max}deg-$j"
hepmc_file="${WRKDIR}/gen_${info_string}.hepmc"
sim_file="${WRKDIR}/sim_${info_string}.edm4hep.root"
rec_file_no_ext="${OUTDIR}/rec_${info_string}"

export DETECTOR_PATH=$EIC_SHELL_PREFIX/../epic
export BEAMLINE_PATH=$EIC_SHELL_PREFIX/../epic/ip6
#export JANA_PLUGIN_PATH=$EIC_SHELL_PREFIX/lib/EICrecon/plugins

# Generating hepmc file
root -l -b -q "./hepmc_generation/gen_particles.cxx+(\
${num_events},\
\"${hepmc_file}\",\
\"${particle}\",\
${theta_min},\
${theta_max},\
${phi_min},\
${phi_max},\
${beam_energy})"

# Running simulation
cd ../epic
npsim --runType batch \
      -v WARNING \
      --part.minimalKineticEnergy "${min_e}*GeV" \
      --physics.list "FTFP_BERT_HP" \
      --physics.rangecut "None" \
      --numberOfEvents ${num_events} \
      --compactFile ${compact_file} \
      --inputFiles ${hepmc_file} \
      --outputFile ${sim_file}

# Running JANA
cd ../EICrecon
python3 src/tools/default_flags_table/reco_flags.py \
        --nevents ${num_events} \
        --xml_files ${compact_file} \
        ${sim_file} \
        ${rec_file_no_ext}

# Deleting hepmc_file
rm -f ${hepmc_file}
