#!/bin/bash
# Usage: run_sim_hepmc <proc> <particle>
set -o errexit

# Setup environment
export DETECTOR_PATH=$EIC_SHELL_PREFIX/../epic
export BEAMLINE_PATH=$EIC_SHELL_PREFIX/../ip6
#export JANA_HOME=$EIC_SHELL_PREFIX
#export JANA_PLUGIN_PATH=$EIC_SHELL_PREFIX/lib/EICrecon/plugins

# Input simulation parameters
particle="$2"
energies=(0.1 0.2 0.5 1 2 5 10 20 40 60)
#energies=(65 70 80 90 100)
j=$(( $1 % 10 ))
k=$(( $1 / 10 ))
beam_energy=${energies[$k]}
min_e=$(echo "$beam_energy * 0.02" | bc)
num_events=1000
theta_min=15 # in degrees
theta_max=25 # in degrees
phi_min=0 # in degrees
phi_max=360 # in degrees 
physics_list="FTFP_BERT_HP"

OUTDIR=$SPIN/data/eic/endcap
WRKDIR=${OUTDIR}
#WRKDIR=${_CONDOR_SCRATCH_DIR}
mkdir -p ${OUTDIR} ${WRKDIR}

# Output file names
compact_file=${DETECTOR_PATH}/epic_pecal.xml
info_string="${particle}_${beam_energy}GeV_theta_${theta_min}_${theta_max}deg-$j"
hepmc_file="${WRKDIR}/gen_${info_string}.hepmc"
sim_file="${WRKDIR}/sim_${info_string}.edm4hep.root"
rec_file_no_ext="${OUTDIR}/rec_${info_string}"

# Generating hepmc file
root -l -b -q "./hepmc_generation/gen_particles.cxx+(\
${num_events},\
\"${hepmc_file}\",\
\"${particle}\",\
${theta_min},\
${theta_max},\
${phi_min},\
${phi_max},\
${beam_energy})"

# Running simulation
cd ../epic
npsim --runType batch \
      -v WARNING \
      --part.minimalKineticEnergy "${min_e}*GeV" \
      --physics.list "FTFP_BERT_HP" \
      --physics.rangecut "None" \
      --numberOfEvents ${num_events} \
      --compactFile ${compact_file} \
      --inputFiles ${hepmc_file} \
      --outputFile ${sim_file}

# Running JANA
cd ../EICrecon
eicrecon -Pjana:debug_plugin_loading=1 \
         -Pjana:nevents=${num_events} \
         -Pacts:MaterialMap=calibrations/materials-map.cbor \
         -Pdd4hep:xml_files=${compact_file} \
         -PBEMC:EcalBarrelScFiRawHits:signalSumFields="" \
         -Ppodio:output_file=${rec_file_no_ext}.tree.edm4eic.root \
         -Phistsfile=${rec_file_no_ext}.ana.root \
         ${sim_file}

#python3 ../analysis/attic/reco_flags.py \
#        --nevents ${num_events} \
#        --xml_files ${compact_file} \
#        ${sim_file} \
#        ${rec_file_no_ext}

# Deleting hepmc_file
rm -f ${hepmc_file}
